name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: debug
      run: pkg-config --libs gtest
    - name: setup
      run: sudo apt-get update -y && sudo apt-get install -y g++ build-essential cmake clang-tools clang-format libgtest-dev libpng-dev
    - name: build
      run: cmake . && make
    - name: test
      run: ./tests/testHistogramGenerator
    
